language: python
python:
- '2.6'
- '2.7'
sudo: false
cache:
- apt
- pip
install:
- pip install -r requirements-test.txt -e .
- pip install coverage coveralls Mako
before_script:
- redis-server --port 6399 &
- redis-server --port 6400 &
- redis-cli -p 6400 config set requirepass foobared
script: py.test --cov flask_bitmapist --cov-report term-missing --pep8 --flakes
after_success:
- coveralls
notifications:
  slack:
    rooms:
      secure: Tok8grsXdoAXuWhig0fO66CLW4SvQsSaRZJ0ZZ/2bkt276LrggcgdNYwSJs4qDuMYz1/eMFASLe0obfgd0EKtliHIZFQLW05aoLKABj6N0k0XhIrqkWWhwhYdL+P8rnsr2VPNEFcX+iXY9V93KBnCBnrixH+J6VaMBr/gvHEZuZbM+gWWDeN/C1P+4T/NtmsvQmSt1jv3pskn7MKpbikIwDNyTvvH1jVPu1mZuaZ0DP2WMO8Pqr1fXsQ3IWlNVULx/JK9wwYRDcCK41qKIjYxUXMYUTkPdxn4aBtJ/oiSNasLwB06x9PYTkbgVoXouj6yxRqJduSR/qCZ/jfaYGAWOhtPVbK3dbUv/qi6gy0Fa62Qd6uFVykUinNPTWz+uNfpmwyO8ZNSKAuyVRMQGJgY9jSXpWaVFQjZVrjyPjfGwo51sqvUYgL3rA8Zq70T4m/Nwb/f7hxHCWZkW0dNopuT3sviBuRBsvdyKvqh51CqKGWI9qV3nxltXjZ9v8GClXXs5PL/spvbmUwa91vgqUSLrK+RttETGxAjoak11A9/SLpXmJcBNBUVMG2xCGUlFR01njyUnPkgSWJI+8oKG1jWER0CvBMDHC8ydToE4sh6I8VPeX1s+G7wpHB9UBmWzOU05SMxrtlzWnDD+NzJTag8/HXN5FIs7DpNoSxTei/lVs=
deploy:
  provider: pypi
  user: cuttlesoft
  password:
    secure: jX4mBERKgONSMyv8/PLuql6Zx59ENngLRPklnrQLbibjyiMaGwdCx0f0C1JsqZu8TsWaEufkYk6I+PZig8Fp3CREYoos1Ayhbi7+Gy96BUn3W5dFeOGoLPOfDKz+9R69JMlDRV3uiM2gRNDS2EmAamI8Dg6nUImiIHpnokMUNpWh8zaGE8f0//viKt8wJkqntmzi6p3ydPwnAu+rMLHaV4vUD1RDu/rBsMCaS0D7HFvEOSr+JyR9IMHD4fmxdypEKamQ7SFwTQH/DituSwNgy/eqxChTc0eNJyYvIsQzqGO9eBozLPfzzmSzvYa2sLIvi/JF6qavgNUS0LrcTcSEgVMgJuBt9Ey+rxNNAq9P3vVwVK1oexx9Hu4LTneSa7WuX17wwKsglQFMzvWXFMj2DzSNhXcDrjgJ//UNnwh5SRdgvUG66yfVkvUm1d1Bqaz2B+BkMMvRS2OLQS23gZEplozA0Vgem5Cij9EUUPYAoliSLLwvhSE6w3/PPevOviCj042+RF1TiTbgEKTxR7fsn7jxKuvpPItI3J/L0cF4LOBwI/7DawA29XB/pBO5bSM48maWzWY3nMkZd2cyOmOa+s+AaAmvuE7XRPeiR/nnYoaF3eYYm7T1EISEDfTkXpFhqDp/6L+m7OzaYgbGyZcXMgHhsc8T69KzR0TeIUb9arc=
  on:
    tags: true
    repo: cuttlesoft/flask-bitmapist
