language: python
python:
- '2.6'
- '2.7'
sudo: false
cache:
- apt
- pip
install:
- pip install -r requirements-test.txt -e .
- pip install coverage coveralls Mako
before_script:
  - redis-server --port 6399 &
script: py.test --cov flask_bitmapist --cov-report term-missing --pep8 --flakes
after_success:
- coveralls
branches:
  only:
  - master
notifications:
  slack:
    rooms:
      secure: Tok8grsXdoAXuWhig0fO66CLW4SvQsSaRZJ0ZZ/2bkt276LrggcgdNYwSJs4qDuMYz1/eMFASLe0obfgd0EKtliHIZFQLW05aoLKABj6N0k0XhIrqkWWhwhYdL+P8rnsr2VPNEFcX+iXY9V93KBnCBnrixH+J6VaMBr/gvHEZuZbM+gWWDeN/C1P+4T/NtmsvQmSt1jv3pskn7MKpbikIwDNyTvvH1jVPu1mZuaZ0DP2WMO8Pqr1fXsQ3IWlNVULx/JK9wwYRDcCK41qKIjYxUXMYUTkPdxn4aBtJ/oiSNasLwB06x9PYTkbgVoXouj6yxRqJduSR/qCZ/jfaYGAWOhtPVbK3dbUv/qi6gy0Fa62Qd6uFVykUinNPTWz+uNfpmwyO8ZNSKAuyVRMQGJgY9jSXpWaVFQjZVrjyPjfGwo51sqvUYgL3rA8Zq70T4m/Nwb/f7hxHCWZkW0dNopuT3sviBuRBsvdyKvqh51CqKGWI9qV3nxltXjZ9v8GClXXs5PL/spvbmUwa91vgqUSLrK+RttETGxAjoak11A9/SLpXmJcBNBUVMG2xCGUlFR01njyUnPkgSWJI+8oKG1jWER0CvBMDHC8ydToE4sh6I8VPeX1s+G7wpHB9UBmWzOU05SMxrtlzWnDD+NzJTag8/HXN5FIs7DpNoSxTei/lVs=
deploy:
  provider: pypi
  user: cuttlesoft
  password:
    secure: QJaZtOuhW3iRcZrwBUXJeT+TNedpbQ+p0/5Hjle+EWEqy8zXj2Qc6Ux34+qcL59WQxqp7QZZSb3xQxzV6CGdghkxTT3QZvSqc0erRawCyyHARTPa8hWcVZTgev+uTwzzbhwV3olslVzTtGmcm8T0AhT6fk77Ae/5rfMso1cZTZJXN5+08OePL5Dq1d2qTpTqaLeRNVKf2Mdybn2TJw4CuhlbaDxf3AIGbHMJNFFN1Vuo68niIWohNVEBuYytTTHRfaNCLNeGRbkGV9mEWyl2IS/j8MXj0fg5zsqllMysaXoFboNVwpHH1ESu0suyXIPzHcg95Fs3ES5djkg/4DqKxL2sSY6OC7TgpB468IFd21XWK6lfldh+6PPsJ1gPLIWcnXlzoSr4XitvpRp2tPX6mfjws4Lg4Hidphf3wBzu/xM780BZDRZipi6ozE3GXy/XX55/ecTp3Ic+fKhLfDqgcLEvoQYJ8RKHMxw09guoGRbYDKtB5AUCVlr1kO5UFvlmk/YQP3BsIqxLrMVKHDE7rFd2/sRAb8RcB4XMZdhhowRoAV5cYPb+2maNVAHgPfMT2iyl4Ze2XbeDClCswAWX+IXwfu27xy4Jwo00drYZfq+9PftoDNRXA0V054KMcXkthNMcdcuYKGlSKRrQMiM20z9zBsmpQtus3QIZbWSZEtM=
  on:
    tags: true
